//! Deterministic JSON Schema emission for the IR wire types.
//!
//! The committed artifacts under `crates/starter-ui-ir/schema/` are
//! regenerated by `cargo run -p starter-ui-ir --bin emit_schema`; the
//! emitter logic lives here so both the binary and the
//! schema-artifact integration test consume the exact same bytes.

use crate::{ActionRequest, ActionResponse, ComponentTree};

/// Pretty-print the `ComponentTree` JSON Schema with a trailing
/// newline. Stable across runs given the same `Cargo.lock` (the
/// underlying `schemars` derive walks the type graph in source order
/// and `serde_json::to_string_pretty` writes keys in insertion
/// order).
pub fn emit_tree_schema() -> String {
    let schema = schemars::schema_for!(ComponentTree);
    pretty(&schema)
}

/// JSON Schema for the `POST /api/v1/ui/action` request body.
pub fn emit_action_request_schema() -> String {
    let schema = schemars::schema_for!(ActionRequest);
    pretty(&schema)
}

/// JSON Schema for the `POST /api/v1/ui/action` response body
/// (post-D1; no `form_errors` variant).
pub fn emit_action_response_schema() -> String {
    let schema = schemars::schema_for!(ActionResponse);
    pretty(&schema)
}

fn pretty<T: serde::Serialize>(schema: &T) -> String {
    let mut s = serde_json::to_string_pretty(schema).expect("schema serialises");
    s.push('\n');
    s
}
