packages:
  - "packages/*"
  - "examples/*"
  - "examples/*/frontend"
  - "examples/*/ui"
  - "starter-extensions/packages/*"
  - "starter-extensions/examples/*"
  - "rubix/packages/*"
  - "rubix/frontend"
  - "rubix/mobile"
