overrides:
  "@types/react": "^19.0.0"
  "@types/react-dom": "^19.0.0"
  react: "19.1.0"
  react-dom: "19.1.0"

peerDependencyRules:
  allowedVersions:
    "@types/react": "19"
    "@types/react-dom": "19"
    react: "19.1.0"
    react-dom: "19.1.0"

packages:
  - "packages/*"
  - "examples/*"
  - "examples/*/frontend"
  - "examples/*/ui"
  - "starter-extensions/packages/*"
  - "starter-extensions/examples/*"
  - "rubix/packages/*"
  - "rubix/extensions/*/ui-src"
  - "rubix/frontend"
  - "rubix/mobile"
  - "rubix/apps/*"

allowBuilds:
  esbuild: true
