include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - riverpod_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Disable public_member_api_docs — not useful for an app (vs library).
    public_member_api_docs: false
