/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsIndexRouteImport } from './routes/flows/index'
import { Route as FlowsFlowIdRouteImport } from './routes/flows/$flowId'
import { Route as AdminWarehouseRouteImport } from './routes/admin/warehouse'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminAccessRouteImport } from './routes/admin/access'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseRoute = AdminWarehouseRouteImport.update({
  id: '/admin/warehouse',
  path: '/admin/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin/access',
  path: '/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extensions': typeof ExtensionsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/flows/': typeof FlowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extensions': typeof ExtensionsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/flows': typeof FlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extensions': typeof ExtensionsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/flows/': typeof FlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/extensions'
    | '/login'
    | '/settings'
    | '/admin/access'
    | '/admin/users'
    | '/admin/warehouse'
    | '/flows/$flowId'
    | '/flows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/extensions'
    | '/login'
    | '/settings'
    | '/admin/access'
    | '/admin/users'
    | '/admin/warehouse'
    | '/flows/$flowId'
    | '/flows'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/extensions'
    | '/login'
    | '/settings'
    | '/admin/access'
    | '/admin/users'
    | '/admin/warehouse'
    | '/flows/$flowId'
    | '/flows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExtensionsRoute: typeof ExtensionsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AdminAccessRoute: typeof AdminAccessRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarehouseRoute: typeof AdminWarehouseRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse': {
      id: '/admin/warehouse'
      path: '/admin/warehouse'
      fullPath: '/admin/warehouse'
      preLoaderRoute: typeof AdminWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExtensionsRoute: ExtensionsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AdminAccessRoute: AdminAccessRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarehouseRoute: AdminWarehouseRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  FlowsIndexRoute: FlowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
