/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsIndexRouteImport } from './routes/flows/index'
import { Route as ExtensionsIndexRouteImport } from './routes/extensions.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as FlowsFlowIdRouteImport } from './routes/flows/$flowId'
import { Route as DashboardsPageIdRouteImport } from './routes/dashboards/$pageId'
import { Route as AdminWarehouseExplorerRouteImport } from './routes/admin/warehouse-explorer'
import { Route as AdminWarehouseRouteImport } from './routes/admin/warehouse'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminConsoleRouteImport } from './routes/admin/console'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as ExtensionsExtIdSplatRouteImport } from './routes/extensions.$extId.$'
import { Route as DashboardsPageIdEditRouteImport } from './routes/dashboards/$pageId_.edit'
import { Route as AdminAccessSplatRouteImport } from './routes/admin/access.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsIndexRoute = ExtensionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExtensionsRoute,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsPageIdRoute = DashboardsPageIdRouteImport.update({
  id: '/dashboards/$pageId',
  path: '/dashboards/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseExplorerRoute = AdminWarehouseExplorerRouteImport.update({
  id: '/admin/warehouse-explorer',
  path: '/admin/warehouse-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseRoute = AdminWarehouseRouteImport.update({
  id: '/admin/warehouse',
  path: '/admin/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin/console',
  path: '/admin/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin/access',
  path: '/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsExtIdSplatRoute = ExtensionsExtIdSplatRouteImport.update({
  id: '/$extId/$',
  path: '/$extId/$',
  getParentRoute: () => ExtensionsRoute,
} as any)
const DashboardsPageIdEditRoute = DashboardsPageIdEditRouteImport.update({
  id: '/dashboards/$pageId_/edit',
  path: '/dashboards/$pageId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessSplatRoute = AdminAccessSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminAccessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/console': typeof AdminConsoleRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/admin/warehouse-explorer': typeof AdminWarehouseExplorerRoute
  '/dashboards/$pageId': typeof DashboardsPageIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/flows/': typeof FlowsIndexRoute
  '/admin/access/$': typeof AdminAccessSplatRoute
  '/dashboards/$pageId/edit': typeof DashboardsPageIdEditRoute
  '/extensions/$extId/$': typeof ExtensionsExtIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/console': typeof AdminConsoleRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/admin/warehouse-explorer': typeof AdminWarehouseExplorerRoute
  '/dashboards/$pageId': typeof DashboardsPageIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/extensions': typeof ExtensionsIndexRoute
  '/flows': typeof FlowsIndexRoute
  '/admin/access/$': typeof AdminAccessSplatRoute
  '/dashboards/$pageId/edit': typeof DashboardsPageIdEditRoute
  '/extensions/$extId/$': typeof ExtensionsExtIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/console': typeof AdminConsoleRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/admin/warehouse-explorer': typeof AdminWarehouseExplorerRoute
  '/dashboards/$pageId': typeof DashboardsPageIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/flows/': typeof FlowsIndexRoute
  '/admin/access/$': typeof AdminAccessSplatRoute
  '/dashboards/$pageId_/edit': typeof DashboardsPageIdEditRoute
  '/extensions/$extId/$': typeof ExtensionsExtIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/extensions'
    | '/login'
    | '/settings'
    | '/admin/access'
    | '/admin/console'
    | '/admin/users'
    | '/admin/warehouse'
    | '/admin/warehouse-explorer'
    | '/dashboards/$pageId'
    | '/flows/$flowId'
    | '/dashboards/'
    | '/extensions/'
    | '/flows/'
    | '/admin/access/$'
    | '/dashboards/$pageId/edit'
    | '/extensions/$extId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/admin/access'
    | '/admin/console'
    | '/admin/users'
    | '/admin/warehouse'
    | '/admin/warehouse-explorer'
    | '/dashboards/$pageId'
    | '/flows/$flowId'
    | '/dashboards'
    | '/extensions'
    | '/flows'
    | '/admin/access/$'
    | '/dashboards/$pageId/edit'
    | '/extensions/$extId/$'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/extensions'
    | '/login'
    | '/settings'
    | '/admin/access'
    | '/admin/console'
    | '/admin/users'
    | '/admin/warehouse'
    | '/admin/warehouse-explorer'
    | '/dashboards/$pageId'
    | '/flows/$flowId'
    | '/dashboards/'
    | '/extensions/'
    | '/flows/'
    | '/admin/access/$'
    | '/dashboards/$pageId_/edit'
    | '/extensions/$extId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  ExtensionsRoute: typeof ExtensionsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AdminAccessRoute: typeof AdminAccessRouteWithChildren
  AdminConsoleRoute: typeof AdminConsoleRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarehouseRoute: typeof AdminWarehouseRoute
  AdminWarehouseExplorerRoute: typeof AdminWarehouseExplorerRoute
  DashboardsPageIdRoute: typeof DashboardsPageIdRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
  DashboardsPageIdEditRoute: typeof DashboardsPageIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/': {
      id: '/extensions/'
      path: '/'
      fullPath: '/extensions/'
      preLoaderRoute: typeof ExtensionsIndexRouteImport
      parentRoute: typeof ExtensionsRoute
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$pageId': {
      id: '/dashboards/$pageId'
      path: '/dashboards/$pageId'
      fullPath: '/dashboards/$pageId'
      preLoaderRoute: typeof DashboardsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse-explorer': {
      id: '/admin/warehouse-explorer'
      path: '/admin/warehouse-explorer'
      fullPath: '/admin/warehouse-explorer'
      preLoaderRoute: typeof AdminWarehouseExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse': {
      id: '/admin/warehouse'
      path: '/admin/warehouse'
      fullPath: '/admin/warehouse'
      preLoaderRoute: typeof AdminWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$extId/$': {
      id: '/extensions/$extId/$'
      path: '/$extId/$'
      fullPath: '/extensions/$extId/$'
      preLoaderRoute: typeof ExtensionsExtIdSplatRouteImport
      parentRoute: typeof ExtensionsRoute
    }
    '/dashboards/$pageId_/edit': {
      id: '/dashboards/$pageId_/edit'
      path: '/dashboards/$pageId/edit'
      fullPath: '/dashboards/$pageId/edit'
      preLoaderRoute: typeof DashboardsPageIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access/$': {
      id: '/admin/access/$'
      path: '/$'
      fullPath: '/admin/access/$'
      preLoaderRoute: typeof AdminAccessSplatRouteImport
      parentRoute: typeof AdminAccessRoute
    }
  }
}

interface ExtensionsRouteChildren {
  ExtensionsIndexRoute: typeof ExtensionsIndexRoute
  ExtensionsExtIdSplatRoute: typeof ExtensionsExtIdSplatRoute
}

const ExtensionsRouteChildren: ExtensionsRouteChildren = {
  ExtensionsIndexRoute: ExtensionsIndexRoute,
  ExtensionsExtIdSplatRoute: ExtensionsExtIdSplatRoute,
}

const ExtensionsRouteWithChildren = ExtensionsRoute._addFileChildren(
  ExtensionsRouteChildren,
)

interface AdminAccessRouteChildren {
  AdminAccessSplatRoute: typeof AdminAccessSplatRoute
}

const AdminAccessRouteChildren: AdminAccessRouteChildren = {
  AdminAccessSplatRoute: AdminAccessSplatRoute,
}

const AdminAccessRouteWithChildren = AdminAccessRoute._addFileChildren(
  AdminAccessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  ExtensionsRoute: ExtensionsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AdminAccessRoute: AdminAccessRouteWithChildren,
  AdminConsoleRoute: AdminConsoleRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarehouseRoute: AdminWarehouseRoute,
  AdminWarehouseExplorerRoute: AdminWarehouseExplorerRoute,
  DashboardsPageIdRoute: DashboardsPageIdRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  FlowsIndexRoute: FlowsIndexRoute,
  DashboardsPageIdEditRoute: DashboardsPageIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
