//! Barcode / scan-to-dashboard provisioning (BARCODE.md).
//!
//! Self-contained, `bc_*`-scoped feature: decode a sticker into an
//! identity, look the device up in a YAML template, and CRUD the
//! catalog rows (device + points + widgets + alarms) that make it
//! show on a dashboard, trending and alarming. Deleting this module +
//! the `bc_*` manifest entries removes the feature wholesale
//! (BARCODE.md §11).
//!
//! Module layout follows one-verb-per-file (FILE-LAYOUT.md):
//!  - [`decode`] — barcode string → [`identity::ScannedIdentity`].
//!  - [`template`] / [`template_store`] — YAML parse, expand, persist.
//!  - [`placement`] — resolve/create site, location, page.
//!  - [`points`] / [`alarms`] / [`widgets`] — template → catalog rows.
//!  - [`device`] — device row build, update, decommission.
//!  - [`orchestrate`] — `bc_provision`, tying the above together.
//!  - [`label`] — printable label render.
//!  - [`crud`] / [`ids`] — shared write helpers and id minting.

mod alarms;
mod assign_page;
pub mod decode;
mod device;
pub mod ids;
pub mod identity;
mod label;
mod orchestrate;
mod pages;
mod placement;
mod points;
pub mod template;
mod template_store;
mod widgets;

pub mod crud;

use starter_ext_sdk::serde_json::{json, Value};

// The capability bundle generated by `requires!` in `extension.rs`.
// Re-exported here so the verb modules can name `crate::provision::RubixOsCtx`.
pub use crate::extension::RubixOsCtx;

/// `bc_decode` — barcode → identity + resolved template summary.
/// Pure of provisioning side effects; it only *reads* templates to
/// resolve the model.
pub fn handle_decode(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    let barcode = crud::take_str(params, "barcode", "bc_decode")?;
    let identity = decode::decode(&barcode)?;
    let known = template_store::known_models(ctx);
    // Resolve the template if known; otherwise return identity with an
    // empty template + the known-models list (friendly, never a 500).
    let template_summary = match template_store::load(ctx, &identity.model) {
        Ok(tpl) => tpl.decode_summary(),
        Err(_) => json!(null),
    };
    Ok(identity.to_decode_output(template_summary, known))
}

/// `bc_provision` — the orchestrator.
pub fn handle_provision(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    orchestrate::handle(ctx, params)
}

/// `bc_device_update`.
pub fn handle_device_update(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    device::handle_update(ctx, params)
}

/// `bc_device_decommission`.
pub fn handle_device_decommission(
    ctx: &RubixOsCtx,
    params: &Value,
) -> starter_ext_sdk::Result<Value> {
    device::handle_decommission(ctx, params)
}

/// `bc_device_assign_page` — place a pending device on a page, generate
/// its widgets, and flip its status to `provisioned`.
pub fn handle_device_assign_page(
    ctx: &RubixOsCtx,
    params: &Value,
) -> starter_ext_sdk::Result<Value> {
    assign_page::handle(ctx, params)
}

/// `bc_site_create`.
pub fn handle_site_create(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    crud::crud_insert(ctx, params, "bc_sites", "site_id", "bc_site_create")
}

/// `bc_location_create`.
pub fn handle_location_create(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    crud::crud_insert(ctx, params, "bc_locations", "location_id", "bc_location_create")
}

/// `bc_page_create`.
pub fn handle_page_create(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    crud::crud_insert(ctx, params, "bc_pages", "page_id", "bc_page_create")
}

/// `bc_page_update` — rename or re-pin a page (by `page_id`).
pub fn handle_page_update(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    pages::handle_update(ctx, params)
}

/// `bc_page_delete` — delete a page; drop its widgets and detach (keep)
/// the devices placed on it as `pending`.
pub fn handle_page_delete(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    pages::handle_delete(ctx, params)
}

/// `bc_template_upsert`.
pub fn handle_template_upsert(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    template_store::handle_upsert(ctx, params)
}

/// `bc_label_render`.
pub fn handle_label_render(ctx: &RubixOsCtx, params: &Value) -> starter_ext_sdk::Result<Value> {
    label::handle(ctx, params)
}
