// `/auth/*` client methods. Cookie-based; the client never handles
// raw tokens — the browser handles the session cookie automatically
// via the shared `fetchJson` / `fetchVoid` helpers (which set
// `credentials: "include"`).
//
// Wire types come from `../generated/index.ts` (regenerated by
// `pnpm codegen`). Mutating endpoints echo the CSRF token from the
// `starter_csrf` cookie back as `X-CSRF-Token` via `readCsrfHeader`.

import { StarterClient } from "../client/client.js";
import { readCsrfHeader } from "../client/csrf.js";
import { fetchJson } from "../client/fetch_json.js";
import { fetchVoid } from "../client/fetch_void.js";
import type { components } from "../generated/index.js";

export type LoginRequest = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type MeResponse = components["schemas"]["MeResponse"];

declare module "../client/client.js" {
  interface StarterClient {
    login(request: LoginRequest): Promise<LoginResponse>;
    logout(): Promise<void>;
    me(): Promise<MeResponse>;
  }
}

StarterClient.prototype.login = function login(this: StarterClient, request: LoginRequest): Promise<LoginResponse> {
  return fetchJson<LoginResponse>(this, `/auth/login`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(request),
  });
};

StarterClient.prototype.logout = async function logout(this: StarterClient): Promise<void> {
  await fetchVoid(this, `/auth/logout`, { method: "POST", headers: readCsrfHeader() });
};

StarterClient.prototype.me = function me(this: StarterClient): Promise<MeResponse> {
  return fetchJson<MeResponse>(this, `/auth/me`);
};
