// `/auth/*` client methods. Cookie-based; the client never handles
// raw tokens — the browser handles the session cookie automatically
// when `credentials: "include"` is set.
//
// Wire types come from `../generated/index.ts` (regenerated by
// `pnpm codegen`). Mutating endpoints echo the CSRF token from the
// `starter_csrf` cookie back as `X-CSRF-Token`.

import { StarterClient } from "../client/client.js";
import { StarterError } from "../error/starter-error.js";
import type { components } from "../generated/index.js";

export type LoginRequest = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type MeResponse = components["schemas"]["MeResponse"];

const CSRF_COOKIE = "starter_csrf";

declare module "../client/client.js" {
  interface StarterClient {
    login(request: LoginRequest): Promise<LoginResponse>;
    logout(): Promise<void>;
    me(): Promise<MeResponse>;
  }
}

StarterClient.prototype.login = async function login(
  this: StarterClient,
  request: LoginRequest,
): Promise<LoginResponse> {
  const res = await this.fetch(`${this.baseUrl}/auth/login`, {
    method: "POST",
    credentials: "include",
    headers: { ...this.headers, "content-type": "application/json" },
    body: JSON.stringify(request),
  });
  if (!res.ok) throw await StarterError.fromResponse(res);
  return (await res.json()) as LoginResponse;
};

StarterClient.prototype.logout = async function logout(this: StarterClient): Promise<void> {
  const csrf = readCookie(CSRF_COOKIE);
  const headers: Record<string, string> = { ...this.headers };
  if (csrf) headers["X-CSRF-Token"] = csrf;
  const res = await this.fetch(`${this.baseUrl}/auth/logout`, {
    method: "POST",
    credentials: "include",
    headers,
  });
  if (!res.ok) throw await StarterError.fromResponse(res);
};

StarterClient.prototype.me = async function me(this: StarterClient): Promise<MeResponse> {
  const res = await this.fetch(`${this.baseUrl}/auth/me`, {
    credentials: "include",
    headers: this.headers,
  });
  if (!res.ok) throw await StarterError.fromResponse(res);
  return (await res.json()) as MeResponse;
};

function readCookie(name: string): string | undefined {
  if (typeof document === "undefined") return undefined;
  for (const part of document.cookie.split(";")) {
    const [k, v] = part.trim().split("=");
    if (k === name) return v;
  }
  return undefined;
}
