//! The flavour-agnostic [`ExtensionBehavior`] trait.
//!
//! Per SCOPE.md **R1**: an extension author writes one trait impl. The same
//! source compiles to **builtin**, **wasm**, or **process** via
//! mutually-exclusive cargo features in `starter-ext-sdk`. The methods do
//! not differ between flavours; only the entry-point glue does.
//!
//! Per **R5**: methods take `&self`, never `&mut self`. The extension
//! struct holds no state — per-instance state lives in the host-provided
//! `Ctx`. This is what keeps the three flavours interchangeable: WASM
//! plugins are fresh per call, in-process plugins live for the host's
//! lifetime, process plugins survive restarts. None of those differences
//! leak through the trait if state is not in the struct.
//!
//! Tool / RPC dispatch is **not** enumerated here. The dispatch table is
//! generated from the manifest's `contributes:` block by
//! `#[derive(Extension)]` in `starter-ext-sdk`; the trait itself only
//! carries the lifecycle hooks every extension shares (R3).

use crate::Result;

/// The single trait an extension author implements.
///
/// `Config` is the deserialised view of the manifest's `config:` payload —
/// validated against the manifest's `config_schema:` at load time, then
/// passed to [`ExtensionBehavior::on_init`] as a typed value.
///
/// `Ctx` is opaque here. In the SDK it is generated by the `requires! {}`
/// macro so the method set on `Ctx` reflects the capabilities the extension
/// declared (R6). `ExtensionBehavior` stays generic over `Ctx` so it can be
/// implemented in the contracts crate without leaking SDK-internal types.
///
/// ## Why no per-handler trait methods
///
/// Tool / route / RPC handlers are dispatched off the manifest's
/// `contributes:` block; the proc-macro in `starter-ext-sdk` reads the
/// manifest at the *extension's* build time and emits a generated dispatch
/// table. A missing handler for a manifest-declared entry (or a handler
/// present for an undeclared entry) is a compile error in the extension,
/// not a runtime error in the host (R3, "Dispatch is manifest-driven").
pub trait ExtensionBehavior: Send + Sync + 'static {
    /// Deserialised manifest `config:` payload.
    type Config: serde::de::DeserializeOwned + Send + Sync + 'static;

    /// Opaque host handle. Method set is determined by the extension's
    /// `requires!{}` declaration at compile time.
    type Ctx: Send + Sync + 'static;

    /// Called once after the manifest validates and the host has linked
    /// in every required capability. `ctx` is alive for the lifetime of
    /// the extension; `cfg` is the parsed `config:` payload.
    ///
    /// Returning `Err` puts the extension in the `Failed` lifecycle state.
    fn on_init(&self, ctx: &Self::Ctx, cfg: &Self::Config) -> Result<()>;

    /// Called when the host is shutting the extension down (operator
    /// `disable`, supervisor restart, host shutdown). Runs inside the
    /// supervisor's grace window; if it does not return in time the
    /// supervisor sends `SIGKILL` (R9 / supervisor semantics).
    fn on_shutdown(&self, ctx: &Self::Ctx) -> Result<()>;
}
