//! Traits the `#[derive(Extension)]` proc-macro generates impls for.
//!
//! These traits live in the SDK (not in `starter-ext-spi`) because they
//! reference SDK-private machinery: the `requires!{}`-generated `Ctx`
//! newtype and the per-flavour dispatch table. The contracts crate stays
//! free of SDK-internal types per SCOPE R2.

use starter_ext_spi::{ExtensionId, Manifest, Result};

/// The static metadata `#[derive(Extension)]` exposes per extension.
///
/// Every method is `&'static` because the manifest is read once, at
/// startup, and never templated — SCOPE R3 + R7. The host caches the
/// returned references; mutation between calls is impossible by design.
pub trait ExtensionMeta {
    /// Reverse-DNS extension id. Validated by `ExtensionId::new` at the
    /// first call; the proc-macro already checked it at the extension's
    /// compile time, so the `expect` inside the generated body cannot
    /// fail in a well-built bundle.
    fn id() -> &'static ExtensionId;

    /// Extension version (semver) read from `block.yaml`.
    fn version() -> &'static semver::Version;

    /// Raw `block.yaml` bytes embedded at the extension's compile time.
    /// SCOPE R7: never runtime-templated; what the host reads here is
    /// byte-identical to what an LLM/MCP client sees and what
    /// `GET /extensions/<id>` returns.
    fn manifest_yaml() -> &'static str;

    /// Lazily-parsed view of [`Self::manifest_yaml`] as the shared
    /// `Manifest` struct.
    fn manifest_static() -> &'static Manifest;
}

/// The manifest-driven dispatch table the proc-macro generates per
/// extension. SCOPE R3: tool dispatch is not enumerated on
/// `ExtensionBehavior`; it lives here, generated from the manifest.
///
/// Adapter crates (`starter-ext-mcp-adapter`, `starter-ext-rest-adapter`,
/// …) call into this trait by `tool_id` strings; the proc-macro emits a
/// `match` that routes to the right `<Struct>ToolHandlers` method.
///
/// A handler missing for a manifest-declared tool ⇒ the
/// `<Struct>ToolHandlers` trait impl is incomplete ⇒ compile error in
/// the extension. An extra handler ⇒ "method not a member of trait" ⇒
/// compile error in the extension. The host sees neither.
pub trait ExtensionDispatch: ExtensionMeta {
    /// The per-extension Ctx newtype generated by `requires!{}`.
    type Ctx;

    /// The tool ids declared in `block.yaml`, in declaration order. Used
    /// by adapters to enumerate routes without re-parsing the manifest.
    fn declared_tool_ids() -> &'static [&'static str];

    /// Invoke the handler for `tool_id` with `params`. Returns
    /// `Error::Validation` if `tool_id` is not declared by the manifest
    /// (this *cannot* happen if the host honours
    /// [`Self::declared_tool_ids`], but the generated `match` is
    /// exhaustive against typos in the host as a defence in depth).
    fn dispatch_tool(
        &self,
        tool_id: &str,
        ctx: &Self::Ctx,
        params: serde_json::Value,
    ) -> Result<serde_json::Value>;
}
