//! Process-flavour entry-point glue (SCOPE R1: process).
//!
//! A process-flavour extension is a normal binary the supervisor spawns
//! (`runtime.bin` in `block.yaml`). The binary's `main` drives this loop:
//!
//! 1. Read the `init` request the supervisor sends as the first frame
//!    (Content-Length-framed JSON-RPC 2.0, via `starter-jsonrpc-stdio`).
//!    Verify the manifest hash matches the bytes the extension was built
//!    against (`ExtensionMeta::manifest_yaml()` — SCOPE R3). Respond with
//!    an `InitReady` echoing the digest.
//! 2. Loop: read one frame at a time.
//!    - `health` request → reply `{ "ok": true }` so the supervisor's
//!      health-deadline timer clears.
//!    - `shutdown` notification → call `ExtensionBehavior::on_shutdown`,
//!      exit cleanly.
//!    - `tools/<id>` request (where `<id>` is a manifest-declared tool) →
//!      route through `ExtensionDispatch::dispatch_tool`, reply with the
//!      handler's result or error.
//!    - Anything else → JSON-RPC `-32601 method not found`.
//!
//! The binary stays single-threaded (one frame in, one frame out): a
//! process-flavour extension is *not* a real-time control loop and the
//! supervisor sends one request at a time. Adding concurrency here would
//! introduce ordering hazards without throughput.
//!
//! ## Calling shape
//!
//! Extension authors don't call [`run_process_main`] directly — they
//! invoke the [`register_process_main!`](crate::register_process_main)
//! macro, which generates a `fn main()` that builds the per-extension
//! `Ctx` newtype from the SDK-internal `CtxInner` (the same trick
//! [`crate::register_static_table!`] uses for builtin).

use std::sync::Arc;
use std::time::Duration;

use serde_json::json;
use tokio::io::BufReader;

use starter_ext_spi::{jsonrpc::JSONRPC_VERSION, Capability, Error, FrameMeta, Result};

use crate::ctx::{CtxInner, EventSender, NeverCancel};
use crate::host_backends::{
    RealAuthzBackend, RealDashboardBackend, RealDatasourceBackend, RealEventBusBackend,
    RealExtensionCallBackend, RealFsBackend, RealHttpOutBackend, RealSecretsBackend,
    RealTracingBackend, RealWallClockBackend, RealWarehouseReadBackend, RealWarehouseWriteBackend,
};
use crate::host_rpc::{self, HostRpc};
use crate::meta::{ExtensionDispatch, ExtensionMeta};

/// Run the process-flavour main loop until the supervisor asks us to
/// shut down or stdin closes.
///
/// `instance` is the extension's unit struct (it has no state — SCOPE
/// R5). `wrap_ctx` is supplied by [`register_process_main!`] and re-
/// wraps the SDK-internal [`CtxInner`] into the per-extension `Ctx`
/// newtype generated by `requires!{}`.
///
/// Returns `Ok(())` on a clean shutdown; any error propagates so the
/// child process exits non-zero and the supervisor records a crash.
pub async fn run_process_main<E, Wrap>(instance: E, wrap_ctx: Wrap) -> Result<()>
where
    E: ExtensionDispatch + Send + Sync + 'static,
    E::Ctx: Send + 'static,
    Wrap: Fn(CtxInner) -> E::Ctx,
{
    let instance = std::sync::Arc::new(instance);
    let mut stdin = BufReader::new(tokio::io::stdin());
    let mut stdout = tokio::io::stdout();

    // ----- Init handshake (SCOPE R3) -----
    let init_frame = read_frame_or_err(&mut stdin).await?;
    let init_req: serde_json::Value = serde_json::from_slice(&init_frame)
        .map_err(|e| Error::transport(format!("init not JSON: {e}")))?;
    let init_id = init_req
        .get("id")
        .cloned()
        .unwrap_or(serde_json::Value::Null);

    let params = init_req
        .get("params")
        .cloned()
        .unwrap_or(serde_json::Value::Null);
    let supplied_hash = params
        .get("manifest_hash")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    // `config` is part of the v0.1 handshake shape but the kernel does
    // not yet route it through to a `Config` type — see SCOPE.md "What
    // each crate / package owns: ExtensionBehavior" for the eventual
    // shape. The supplied value is echoed back in the ready response so
    // adapters that introspect the handshake can see what the operator
    // supplied; the extension itself does not act on it in v0.1.
    let _config_value = params
        .get("config")
        .cloned()
        .unwrap_or(serde_json::Value::Null);

    let our_hash = own_manifest_hash::<E>();
    if supplied_hash != our_hash {
        // We still send a response so the supervisor sees the mismatch
        // and surfaces a clear error rather than a timeout.
        let resp = json!({
            "jsonrpc": JSONRPC_VERSION,
            "id": init_id,
            "result": {
                "manifest_hash": our_hash,
                "ready": false,
                "reason": "manifest hash differs from supervisor",
            },
        });
        write_value(&mut stdout, &resp).await?;
        return Err(Error::spawn("manifest hash mismatch at child"));
    }

    // ----- Init response (still goes through a direct stdout write
    // because the writer task hasn't spawned yet). -----
    let resp = json!({
        "jsonrpc": JSONRPC_VERSION,
        "id": init_id,
        "result": {
            "manifest_hash": our_hash,
            "ready": true,
        },
    });
    write_value(&mut stdout, &resp).await?;

    // ----- Wire the outbound JSON-RPC channel + writer task. -----
    //
    // Every frame the child sends after init goes through this
    // mpsc channel: handler responses *and* outbound host calls
    // (`dashboard.read`, `authz.check`, …) share one writer task
    // so the two write halves can't race for stdout. The pending
    // map is shared between the `HostRpc` (call-side inserts) and
    // the inbound read loop (response-side removes via
    // `host_rpc::route_response`).
    let (writer_tx, mut writer_rx) = tokio::sync::mpsc::unbounded_channel::<serde_json::Value>();
    let pending = host_rpc::new_pending_map();
    let host_rpc = HostRpc::new(writer_tx.clone(), pending.clone());

    let writer_task = tokio::spawn(async move {
        while let Some(value) = writer_rx.recv().await {
            if let Err(e) = write_value(&mut stdout, &value).await {
                // stdout has broken — the supervisor will observe
                // the closed pipe and treat this as a crash. We
                // print to stderr so the supervisor's stderr ring
                // captures the reason. No `tracing` dep on
                // `starter-ext-sdk` at the `process` feature, so
                // a plain `eprintln!` is the right tool here.
                eprintln!("starter-ext-sdk::process writer task: {e}");
                break;
            }
        }
    });

    // Build the Ctx the handler will see. Row-5-adjacent backends
    // hop to the host via `HostRpc`; the other five categories
    // still resolve to `Stub<Cap>` impls until their host methods
    // light up.
    let (event_tx, _event_rx) = tokio::sync::mpsc::channel(64);
    let ctx_inner = real_ctx_inner(event_tx, host_rpc.clone());
    // Construct an initial Ctx wrapper for the init handshake — system
    // frame, no caller. Per-call Ctx newtypes are reconstructed in the
    // dispatch loop below with `with_caller`.
    let ctx = wrap_ctx(ctx_inner.clone());

    // SCOPE.md "What each crate / package owns: ExtensionBehavior"
    // describes a typed `on_init(ctx, cfg)` hook; v0.1's process flavour
    // does not invoke it from this entry-point because the proc-macro
    // does not currently require the extension to implement
    // `ExtensionBehavior` for builtin (the existing hello-builtin
    // example only implements the handler trait). Calling on_init here
    // would diverge the two flavours' compile-time surface, which R1
    // rules out. Wiring lifecycle hooks lands additively in a later
    // stage alongside the unified `ExtensionBehavior` requirement.
    let _ = &ctx;

    // Helper: send a frame through the writer task; surface a
    // `Transport` error when the writer task has dropped (rare:
    // means stdout broke or the task itself panicked).
    let send_frame = |value: serde_json::Value| -> Result<()> {
        writer_tx
            .send(value)
            .map_err(|_| Error::transport("writer task closed"))
    };

    // ----- Main dispatch loop -----
    let exit_reason = loop {
        let frame = match starter_jsonrpc_stdio::read_frame(&mut stdin).await {
            Ok(Some(b)) => b,
            Ok(None) => break Ok(()), // clean EOF — supervisor closed us
            Err(e) => break Err(Error::transport(format!("read frame: {e}"))),
        };
        let value: serde_json::Value = match serde_json::from_slice(&frame) {
            Ok(v) => v,
            Err(e) => break Err(Error::transport(format!("frame JSON: {e}"))),
        };

        // Is this a response to one of our outbound host calls?
        // If so, the demultiplexer wakes the awaiting caller and
        // we go straight back to reading.
        if host_rpc::route_response(&pending, &value) {
            continue;
        }

        let method = value
            .get("method")
            .and_then(|m| m.as_str())
            .unwrap_or_default()
            .to_string();
        let id_opt = value.get("id").cloned();
        let params = value
            .get("params")
            .cloned()
            .unwrap_or(serde_json::Value::Null);

        // Notification → no response.
        if id_opt.is_none() {
            if method == "shutdown" {
                // See note in init: on_shutdown lands with the unified
                // `ExtensionBehavior` requirement. v0.1 exits cleanly.
                break Ok(());
            }
            continue;
        }

        let id = id_opt.unwrap();
        match method.as_str() {
            "health" => {
                let resp = json!({
                    "jsonrpc": JSONRPC_VERSION,
                    "id": id,
                    "result": { "ok": true },
                });
                if let Err(e) = send_frame(resp) {
                    break Err(e);
                }
            }
            "shutdown" => {
                let resp = json!({
                    "jsonrpc": JSONRPC_VERSION,
                    "id": id,
                    "result": { "ok": true },
                });
                let _ = send_frame(resp);
                break Ok(());
            }
            m if m.starts_with("tools/") => {
                let tool_id = m["tools/".len()..].to_string();
                // Extract `_meta.caller` from the inbound frame (absent
                // → host-internal call). Cloning per-invocation keeps
                // the per-call Ctx newtype's identity view immutable.
                let caller = value
                    .get("_meta")
                    .and_then(|m| serde_json::from_value::<FrameMeta>(m.clone()).ok())
                    .and_then(|m| m.caller);
                let per_call_ctx = wrap_ctx(ctx_inner.clone().with_caller(caller.clone()));
                // Dispatch on `spawn_blocking` so the read loop keeps
                // reading frames while the handler runs. Critical for
                // host-RPC categories (`warehouse.write`, etc.) whose
                // `HostRpc::call_sync` blocks on a response that this
                // very read loop must demultiplex — running the
                // handler inline would deadlock the call.
                let instance_arc = std::sync::Arc::clone(&instance);
                let writer_tx_handler = writer_tx.clone();
                let tool_id_for_task = tool_id.clone();
                let id_for_task = id.clone();
                tokio::task::spawn_blocking(move || {
                    // Bind the caller on the blocking task so any
                    // outbound `HostRpc::call_sync` in the handler
                    // body re-stamps `_meta.caller` on the wire.
                    let dispatch =
                        || instance_arc.dispatch_tool(&tool_id_for_task, &per_call_ctx, params);
                    let result = match caller {
                        Some(c) => crate::caller_local::scope_sync(c, dispatch),
                        None => dispatch(),
                    };
                    let resp = match result {
                        Ok(v) => json!({
                            "jsonrpc": JSONRPC_VERSION,
                            "id": id_for_task,
                            "result": v,
                        }),
                        Err(e) => json!({
                            "jsonrpc": JSONRPC_VERSION,
                            "id": id_for_task,
                            "error": e,
                        }),
                    };
                    // Best-effort: a dropped writer means the
                    // process is already winding down; the
                    // supervisor will observe the closed pipe.
                    let _ = writer_tx_handler.send(resp);
                });
            }
            // FLOW-NODES slice B: the host bridges an extension's
            // `contributes.nodes[]` to this child by a `ProcessNodeProxy` that
            // forwards `NodeBehavior::invoke` over this wire method. A
            // contributed node-kind id IS a tool id (the demo declares each kind
            // both ways and the namespace validator requires the same
            // reverse-DNS id), so a node invoke routes to the SAME
            // `dispatch_tool` handler — the node body and the tool body are one
            // and the same. Without this arm the child answered `flow.node.invoke`
            // with "unknown method", the proxy mapped that to `NodeError::Backend`,
            // and every setup-automation node failed before its side effect ran.
            //
            // Wire shape (see `starter_ext_flow::process_proxy::InvokeParams`):
            //   params = { kind, invocation_id, deadline_ms, input: SlotMap }
            // where SlotMap is `{ <slot>: { "type": .., "value": .. } }`. We
            // unwrap each SlotValue to plain JSON so the tool handler reads
            // `params.barcode` as it always has, then wrap the handler's JSON
            // result back into a SlotMap under `{ "slots": { .. } }`, the shape
            // `parse_response_as_slotmap` expects.
            "flow.node.invoke" => {
                let kind = params
                    .get("kind")
                    .and_then(|k| k.as_str())
                    .unwrap_or_default()
                    .to_string();
                if kind.is_empty() {
                    let err = Error::validation("flow.node.invoke: missing `kind`");
                    let resp = json!({ "jsonrpc": JSONRPC_VERSION, "id": id, "error": err });
                    if let Err(e) = send_frame(resp) {
                        break Err(e);
                    }
                    continue;
                }
                // SlotMap input → plain JSON object the tool handler consumes.
                let tool_params = slotmap_to_params(params.get("input"));
                // Same caller-binding + blocking-dispatch discipline as `tools/`:
                // the handler may issue blocking host RPCs (`warehouse.write`)
                // that this read loop must keep demultiplexing.
                let caller = value
                    .get("_meta")
                    .and_then(|m| serde_json::from_value::<FrameMeta>(m.clone()).ok())
                    .and_then(|m| m.caller);
                let per_call_ctx = wrap_ctx(ctx_inner.clone().with_caller(caller.clone()));
                let instance_arc = std::sync::Arc::clone(&instance);
                let writer_tx_handler = writer_tx.clone();
                let id_for_task = id.clone();
                tokio::task::spawn_blocking(move || {
                    let dispatch = || instance_arc.dispatch_tool(&kind, &per_call_ctx, tool_params);
                    let result = match caller {
                        Some(c) => crate::caller_local::scope_sync(c, dispatch),
                        None => dispatch(),
                    };
                    let resp = match result {
                        // Wrap the handler's JSON output as a SlotMap response.
                        Ok(v) => json!({
                            "jsonrpc": JSONRPC_VERSION,
                            "id": id_for_task,
                            "result": { "slots": params_to_slotmap(&v) },
                        }),
                        Err(e) => json!({
                            "jsonrpc": JSONRPC_VERSION,
                            "id": id_for_task,
                            "error": e,
                        }),
                    };
                    let _ = writer_tx_handler.send(resp);
                });
            }
            other => {
                let err = Error::validation(format!("unknown method {other:?}"));
                let resp = json!({
                    "jsonrpc": JSONRPC_VERSION,
                    "id": id,
                    "error": err,
                });
                if let Err(e) = send_frame(resp) {
                    break Err(e);
                }
            }
        }
    };

    // Drop the call-side sender so the writer task observes the
    // channel close and exits cleanly; await it so the runtime
    // doesn't tear down mid-flush.
    drop(writer_tx);
    let _ = writer_task.await;
    exit_reason
}

/// Unwrap a `flow.node.invoke` `input` SlotMap into the plain JSON object a
/// tool handler reads. Each slot is a tagged `SlotValue`
/// (`{ "type": "string", "value": "ACME-1" }`); the handler expects
/// `{ "barcode": "ACME-1" }`, so we project each slot to its inner value. A
/// missing/!object `input` yields an empty object (the node was seeded with no
/// inputs). The `bytes` variant has no clean JSON scalar form, so its array is
/// passed through under the value as-is.
fn slotmap_to_params(input: Option<&serde_json::Value>) -> serde_json::Value {
    let mut obj = serde_json::Map::new();
    if let Some(map) = input.and_then(|v| v.as_object()) {
        for (slot, sv) in map {
            obj.insert(slot.clone(), slot_value_to_json(sv));
        }
    }
    serde_json::Value::Object(obj)
}

/// Project one tagged `SlotValue` JSON onto its inner value. Unknown/un-tagged
/// shapes pass through unchanged so a future `SlotValue` variant degrades to
/// "hand the handler the raw JSON" rather than dropping the slot.
fn slot_value_to_json(sv: &serde_json::Value) -> serde_json::Value {
    match sv.get("type").and_then(|t| t.as_str()) {
        Some("null") => serde_json::Value::Null,
        Some(_) => sv.get("value").cloned().unwrap_or(serde_json::Value::Null),
        None => sv.clone(),
    }
}

/// Wrap a tool handler's plain JSON output back into a SlotMap for the
/// `flow.node.invoke` response (`{ <field>: { "type": .., "value": .. } }`),
/// the shape `ProcessNodeProxy::parse_response_as_slotmap` reads. The engine
/// then exposes each field as an output slot (e.g. `device_id`) the next node's
/// link can read. A non-object result is returned under a single `out` slot.
fn params_to_slotmap(result: &serde_json::Value) -> serde_json::Value {
    let mut out = serde_json::Map::new();
    match result {
        serde_json::Value::Object(map) => {
            for (k, v) in map {
                out.insert(k.clone(), json_to_slot_value(v));
            }
        }
        other => {
            out.insert("out".to_string(), json_to_slot_value(other));
        }
    }
    serde_json::Value::Object(out)
}

/// Tag a plain JSON value as the matching `SlotValue`. Strings/bools/ints/floats
/// map to their primitive variants; everything else (arrays, objects, null) uses
/// the `json` escape-hatch variant so no information is lost.
fn json_to_slot_value(v: &serde_json::Value) -> serde_json::Value {
    match v {
        serde_json::Value::Null => json!({ "type": "null" }),
        serde_json::Value::Bool(b) => json!({ "type": "bool", "value": b }),
        serde_json::Value::Number(n) if n.is_i64() => {
            json!({ "type": "int", "value": n.as_i64() })
        }
        serde_json::Value::Number(n) => json!({ "type": "float", "value": n.as_f64() }),
        serde_json::Value::String(s) => json!({ "type": "string", "value": s }),
        other => json!({ "type": "json", "value": other }),
    }
}

/// Read one frame or fail with a clear transport error. Wraps the
/// framing crate's `Ok(None)` (clean EOF) into a `Transport` error
/// because losing the supervisor's stdin between handshake and dispatch
/// is unambiguously a crash from the child's perspective.
async fn read_frame_or_err<R>(reader: &mut R) -> Result<Vec<u8>>
where
    R: tokio::io::AsyncBufRead + Unpin,
{
    // Bound the handshake read so a misbehaving supervisor can't wedge us.
    let frame = tokio::time::timeout(
        Duration::from_secs(30),
        starter_jsonrpc_stdio::read_frame(reader),
    )
    .await
    .map_err(|_| Error::transport("timed out waiting for init"))?
    .map_err(|e| Error::transport(format!("init frame: {e}")))?;
    frame.ok_or_else(|| Error::transport("stdin closed before init"))
}

async fn write_value<W>(writer: &mut W, value: &serde_json::Value) -> Result<()>
where
    W: tokio::io::AsyncWrite + Unpin,
{
    let body =
        serde_json::to_vec(value).map_err(|e| Error::transport(format!("serialise: {e}")))?;
    starter_jsonrpc_stdio::write_frame(writer, &body)
        .await
        .map_err(|e| Error::transport(format!("write: {e}")))
}

/// Compute the manifest hash of this extension's own embedded
/// `block.yaml`. Matches the byte-identical comparison the supervisor
/// performs against the bundle's `block.yaml` (SCOPE R3).
fn own_manifest_hash<E: ExtensionMeta>() -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(E::manifest_yaml().as_bytes());
    hex_encode(&h.finalize())
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

/// Build a `CtxInner` whose Row-5-adjacent backends call the
/// host via [`HostRpc::call_sync`] and whose other categories
/// still resolve to the same `Stub<Cap>` impls
/// [`stub_ctx_inner`] uses. The boundary lives here so a future
/// slice that lights up `secrets.get` / `http.request` / `fs.read`
/// / `clock.now` / `tracing.event` can flip each one
/// independently — same shape as the four real backends below.
fn real_ctx_inner(events: EventSender, host_rpc: HostRpc) -> CtxInner {
    // All nine capability categories now hop to the host over
    // `HostRpc::call_sync`. The host enforces each one's manifest
    // allowlist (authorities for http, path specs for fs,
    // prefixes for secrets, …) before fulfilling the call.
    CtxInner::new(
        events,
        Arc::new(NeverCancel),
        Arc::new(RealSecretsBackend::new(host_rpc.clone())),
        Arc::new(RealHttpOutBackend::new(host_rpc.clone())),
        Arc::new(RealFsBackend::new(host_rpc.clone())),
        Arc::new(RealWallClockBackend::new(host_rpc.clone())),
        Arc::new(RealTracingBackend::new(host_rpc.clone())),
        Arc::new(RealWarehouseReadBackend::new(host_rpc.clone())),
        Arc::new(RealWarehouseWriteBackend::new(host_rpc.clone())),
        Arc::new(RealDatasourceBackend::new(host_rpc.clone())),
        Arc::new(RealEventBusBackend::new(host_rpc.clone())),
        Arc::new(RealExtensionCallBackend::new(host_rpc.clone())),
        Arc::new(RealDashboardBackend::new(host_rpc.clone())),
        Arc::new(RealAuthzBackend::new(host_rpc)),
    )
}

/// Silence "unused import" when only `Capability` shows up in docs.
#[allow(dead_code)]
fn _capability_docs_anchor(_c: &Capability) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_encode_round_trip() {
        assert_eq!(hex_encode(&[0xde, 0xad, 0xbe, 0xef]), "deadbeef");
        assert_eq!(hex_encode(&[0, 1, 2]), "000102");
    }
}
