//! Process-flavour entry-point glue (SCOPE R1: process).
//!
//! A process-flavour extension is a normal binary the supervisor spawns
//! (`runtime.bin` in `block.yaml`). The binary's `main` drives this loop:
//!
//! 1. Read the `init` request the supervisor sends as the first frame
//!    (Content-Length-framed JSON-RPC 2.0, via `starter-jsonrpc-stdio`).
//!    Verify the manifest hash matches the bytes the extension was built
//!    against (`ExtensionMeta::manifest_yaml()` — SCOPE R3). Respond with
//!    an `InitReady` echoing the digest.
//! 2. Loop: read one frame at a time.
//!    - `health` request → reply `{ "ok": true }` so the supervisor's
//!      health-deadline timer clears.
//!    - `shutdown` notification → call `ExtensionBehavior::on_shutdown`,
//!      exit cleanly.
//!    - `tools/<id>` request (where `<id>` is a manifest-declared tool) →
//!      route through `ExtensionDispatch::dispatch_tool`, reply with the
//!      handler's result or error.
//!    - Anything else → JSON-RPC `-32601 method not found`.
//!
//! The binary stays single-threaded (one frame in, one frame out): a
//! process-flavour extension is *not* a real-time control loop and the
//! supervisor sends one request at a time. Adding concurrency here would
//! introduce ordering hazards without throughput.
//!
//! ## Calling shape
//!
//! Extension authors don't call [`run_process_main`] directly — they
//! invoke the [`register_process_main!`](crate::register_process_main)
//! macro, which generates a `fn main()` that builds the per-extension
//! `Ctx` newtype from the SDK-internal `CtxInner` (the same trick
//! [`crate::register_static_table!`] uses for builtin).

use std::sync::Arc;
use std::time::Duration;

use serde_json::json;
use tokio::io::BufReader;

use starter_ext_spi::{
    jsonrpc::JSONRPC_VERSION, Capability, Error, Result,
};

use crate::ctx::{
    CtxInner, EventSender, FsBackend, HttpOutBackend, NeverCancel, SecretsBackend,
    TracingBackend, WallClockBackend,
};
use crate::meta::{ExtensionDispatch, ExtensionMeta};

/// Run the process-flavour main loop until the supervisor asks us to
/// shut down or stdin closes.
///
/// `instance` is the extension's unit struct (it has no state — SCOPE
/// R5). `wrap_ctx` is supplied by [`register_process_main!`] and re-
/// wraps the SDK-internal [`CtxInner`] into the per-extension `Ctx`
/// newtype generated by `requires!{}`.
///
/// Returns `Ok(())` on a clean shutdown; any error propagates so the
/// child process exits non-zero and the supervisor records a crash.
pub async fn run_process_main<E, Wrap>(instance: E, wrap_ctx: Wrap) -> Result<()>
where
    E: ExtensionDispatch,
    Wrap: Fn(CtxInner) -> E::Ctx,
{
    let mut stdin = BufReader::new(tokio::io::stdin());
    let mut stdout = tokio::io::stdout();

    // ----- Init handshake (SCOPE R3) -----
    let init_frame = read_frame_or_err(&mut stdin).await?;
    let init_req: serde_json::Value = serde_json::from_slice(&init_frame)
        .map_err(|e| Error::transport(format!("init not JSON: {e}")))?;
    let init_id = init_req
        .get("id")
        .cloned()
        .unwrap_or(serde_json::Value::Null);

    let params = init_req
        .get("params")
        .cloned()
        .unwrap_or(serde_json::Value::Null);
    let supplied_hash = params
        .get("manifest_hash")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    // `config` is part of the v0.1 handshake shape but the kernel does
    // not yet route it through to a `Config` type — see SCOPE.md "What
    // each crate / package owns: ExtensionBehavior" for the eventual
    // shape. The supplied value is echoed back in the ready response so
    // adapters that introspect the handshake can see what the operator
    // supplied; the extension itself does not act on it in v0.1.
    let _config_value = params
        .get("config")
        .cloned()
        .unwrap_or(serde_json::Value::Null);

    let our_hash = own_manifest_hash::<E>();
    if supplied_hash != our_hash {
        // We still send a response so the supervisor sees the mismatch
        // and surfaces a clear error rather than a timeout.
        let resp = json!({
            "jsonrpc": JSONRPC_VERSION,
            "id": init_id,
            "result": {
                "manifest_hash": our_hash,
                "ready": false,
                "reason": "manifest hash differs from supervisor",
            },
        });
        write_value(&mut stdout, &resp).await?;
        return Err(Error::spawn("manifest hash mismatch at child"));
    }

    // Build the Ctx the handler will see. v0.1 host has no out-of-process
    // capability backends wired (those land with the wasm + adapter
    // phases); we hand the extension stub backends that always return
    // `Error::Capability`. The capability gate at the supervisor side is
    // what actually enforces R8 today.
    let (event_tx, _event_rx) = tokio::sync::mpsc::channel(64);
    let ctx_inner = stub_ctx_inner(event_tx);
    let ctx = wrap_ctx(ctx_inner);

    // SCOPE.md "What each crate / package owns: ExtensionBehavior"
    // describes a typed `on_init(ctx, cfg)` hook; v0.1's process flavour
    // does not invoke it from this entry-point because the proc-macro
    // does not currently require the extension to implement
    // `ExtensionBehavior` for builtin (the existing hello-builtin
    // example only implements the handler trait). Calling on_init here
    // would diverge the two flavours' compile-time surface, which R1
    // rules out. Wiring lifecycle hooks lands additively in a later
    // stage alongside the unified `ExtensionBehavior` requirement.
    let _ = &ctx;

    let resp = json!({
        "jsonrpc": JSONRPC_VERSION,
        "id": init_id,
        "result": {
            "manifest_hash": our_hash,
            "ready": true,
        },
    });
    write_value(&mut stdout, &resp).await?;

    // ----- Main dispatch loop -----
    loop {
        let frame = match starter_jsonrpc_stdio::read_frame(&mut stdin).await {
            Ok(Some(b)) => b,
            Ok(None) => return Ok(()), // clean EOF — supervisor closed us
            Err(e) => return Err(Error::transport(format!("read frame: {e}"))),
        };
        let value: serde_json::Value = serde_json::from_slice(&frame)
            .map_err(|e| Error::transport(format!("frame JSON: {e}")))?;

        let method = value
            .get("method")
            .and_then(|m| m.as_str())
            .unwrap_or_default()
            .to_string();
        let id_opt = value.get("id").cloned();
        let params = value
            .get("params")
            .cloned()
            .unwrap_or(serde_json::Value::Null);

        // Notification → no response.
        if id_opt.is_none() {
            if method == "shutdown" {
                // See note in init: on_shutdown lands with the unified
                // `ExtensionBehavior` requirement. v0.1 exits cleanly.
                return Ok(());
            }
            continue;
        }

        let id = id_opt.unwrap();
        match method.as_str() {
            "health" => {
                let resp = json!({
                    "jsonrpc": JSONRPC_VERSION,
                    "id": id,
                    "result": { "ok": true },
                });
                write_value(&mut stdout, &resp).await?;
            }
            "shutdown" => {
                let resp = json!({
                    "jsonrpc": JSONRPC_VERSION,
                    "id": id,
                    "result": { "ok": true },
                });
                write_value(&mut stdout, &resp).await?;
                return Ok(());
            }
            m if m.starts_with("tools/") => {
                let tool_id = &m["tools/".len()..];
                let result = instance.dispatch_tool(tool_id, &ctx, params);
                let resp = match result {
                    Ok(v) => json!({
                        "jsonrpc": JSONRPC_VERSION,
                        "id": id,
                        "result": v,
                    }),
                    Err(e) => json!({
                        "jsonrpc": JSONRPC_VERSION,
                        "id": id,
                        "error": e,
                    }),
                };
                write_value(&mut stdout, &resp).await?;
            }
            other => {
                let err = Error::validation(format!("unknown method {other:?}"));
                let resp = json!({
                    "jsonrpc": JSONRPC_VERSION,
                    "id": id,
                    "error": err,
                });
                write_value(&mut stdout, &resp).await?;
            }
        }
    }
}

/// Read one frame or fail with a clear transport error. Wraps the
/// framing crate's `Ok(None)` (clean EOF) into a `Transport` error
/// because losing the supervisor's stdin between handshake and dispatch
/// is unambiguously a crash from the child's perspective.
async fn read_frame_or_err<R>(reader: &mut R) -> Result<Vec<u8>>
where
    R: tokio::io::AsyncBufRead + Unpin,
{
    // Bound the handshake read so a misbehaving supervisor can't wedge us.
    let frame = tokio::time::timeout(
        Duration::from_secs(30),
        starter_jsonrpc_stdio::read_frame(reader),
    )
    .await
    .map_err(|_| Error::transport("timed out waiting for init"))?
    .map_err(|e| Error::transport(format!("init frame: {e}")))?;
    frame.ok_or_else(|| Error::transport("stdin closed before init"))
}

async fn write_value<W>(writer: &mut W, value: &serde_json::Value) -> Result<()>
where
    W: tokio::io::AsyncWrite + Unpin,
{
    let body = serde_json::to_vec(value)
        .map_err(|e| Error::transport(format!("serialise: {e}")))?;
    starter_jsonrpc_stdio::write_frame(writer, &body)
        .await
        .map_err(|e| Error::transport(format!("write: {e}")))
}

/// Compute the manifest hash of this extension's own embedded
/// `block.yaml`. Matches the byte-identical comparison the supervisor
/// performs against the bundle's `block.yaml` (SCOPE R3).
fn own_manifest_hash<E: ExtensionMeta>() -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(E::manifest_yaml().as_bytes());
    hex_encode(&h.finalize())
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

/// Build a `CtxInner` whose backends all return
/// `Error::Capability(... "not wired in v0.1 ...")`. The supervisor is
/// what enforces capability use at the wire boundary; what the
/// extension's own `Ctx` does inside its address space is informational
/// in v0.1.
fn stub_ctx_inner(events: EventSender) -> CtxInner {
    #[derive(Debug)]
    struct Stub(&'static str);
    impl SecretsBackend for Stub {
        fn get(&self, _name: &str) -> Result<String> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 process flavour",
                self.0
            )))
        }
    }
    impl HttpOutBackend for Stub {
        fn request(&self, _req: serde_json::Value) -> Result<serde_json::Value> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 process flavour",
                self.0
            )))
        }
    }
    impl FsBackend for Stub {
        fn read(&self, _path: &str) -> Result<Vec<u8>> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 process flavour",
                self.0
            )))
        }
    }
    impl WallClockBackend for Stub {
        fn now_unix_ms(&self) -> Result<u64> {
            use std::time::{SystemTime, UNIX_EPOCH};
            Ok(SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0))
        }
    }
    impl TracingBackend for Stub {
        fn event(&self, _level: &str, _msg: &str, _fields: serde_json::Value) {}
    }
    CtxInner::new(
        events,
        Arc::new(NeverCancel),
        Arc::new(Stub("secrets")),
        Arc::new(Stub("http_out")),
        Arc::new(Stub("fs")),
        Arc::new(Stub("wall_clock")),
        Arc::new(Stub("tracing")),
    )
}

/// Silence "unused import" when only `Capability` shows up in docs.
#[allow(dead_code)]
fn _capability_docs_anchor(_c: &Capability) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_encode_round_trip() {
        assert_eq!(hex_encode(&[0xde, 0xad, 0xbe, 0xef]), "deadbeef");
        assert_eq!(hex_encode(&[0, 1, 2]), "000102");
    }
}
