//! WASM-flavour entry-point glue (SCOPE R1: wasm). Stage 11 — Kernel
//! Phase 4.
//!
//! The wasm flavour straddles two compile contexts:
//!
//! - **`wasm32-wasip2`** (the extension's release build, driven by
//!   `cargo component build`): the macro-generated entry-point exports
//!   `starter:extension/guest.dispatch-tool` (defined in
//!   `crates/starter-ext-wasm/wit/starter-extension.wit`). The host
//!   crate (`starter-ext-wasm`) calls into it via wasmtime; the body
//!   routes through [`ExtensionDispatch::dispatch_tool`] just like the
//!   other two flavours.
//! - **Any other target** (the workspace's host-target `cargo test`):
//!   the macro expansion is *inert*. The example crate still compiles
//!   so the smoke test "wasm-feature flips correctly" (the
//!   `__STARTER_EXT_FLAVOUR_MARKER` assertion in [`crate::tests`])
//!   stays green even though no wasm runtime exists on the host.
//!
//! The link-time enforcement R1 promises is not flavour-conditional:
//! every flavour module emits its own copy of the
//! `__STARTER_EXT_FLAVOUR_MARKER` `#[no_mangle]` static (see
//! [`crate`]'s top), so a Cargo.toml that accidentally enables more
//! than one flavour still trips the linker regardless of target.
//!
//! ## v0.1 body
//!
//! The typed wasmtime↔wit_bindgen call into `dispatch-tool` lands in a
//! later minor (`wit_bindgen` and the matching component-model
//! `bindgen!` are deliberately not added in Stage 11 — see the
//! `starter-ext-wasm` host's `WasmCallOutcome::NotImplemented`
//! comment for the matching state). What this module *does* ship is:
//!
//! - A public [`run_wasm_main`] entry-point the
//!   [`crate::register_wasm_main!`] macro hangs off — same shape as
//!   [`crate::process::run_process_main`].
//! - Const re-exports of the host's WIT package name + version so
//!   admin tooling can render the substrate version compatibility
//!   matrix without dragging the wasm host crate in.

use std::sync::Arc;

use serde_json::Value;
use starter_ext_spi::{Error, Result};

use crate::ctx::{
    AuthzBackend, CtxInner, DashboardBackend, DatasourceBackend, EventBusBackend, EventSender,
    FsBackend, HttpOutBackend, NeverCancel, Row, SecretsBackend, TemplateSpec, TracingBackend,
    WallClockBackend, WarehouseReadBackend, WarehouseWriteBackend,
};
use crate::meta::ExtensionDispatch;

/// WIT package the wasm host instantiates extensions against. Matches
/// `crates/starter-ext-wasm/wit/starter-extension.wit`
/// (`package starter:extension@0.1.0`).
pub const WIT_PACKAGE_NAME: &str = "starter:extension";

/// WIT package version. v0.1 is the only major; new minors are
/// additive within `0.1.x`.
pub const WIT_PACKAGE_VERSION: &str = "0.1.0";

/// Drive one `dispatch-tool` call against the extension's typed
/// handlers. Macro-emitted glue only — extensions never call this
/// directly.
///
/// `wrap_ctx` mirrors the parameter on
/// [`crate::process::run_process_main`]: it re-wraps the SDK-internal
/// [`CtxInner`] into the per-extension `Ctx` newtype generated by
/// `requires!{}`, so a wasm-flavour handler sees the same `Ctx` shape
/// a builtin or process-flavour handler sees (R1).
///
/// The function body is intentionally identical to what a future
/// `wit_bindgen::export!` body would call. The signature is the
/// contract; the call path inside it can grow without breaking the
/// macro consumers.
pub fn run_wasm_main<E, Wrap>(
    instance: &E,
    tool_id: &str,
    params: Value,
    wrap_ctx: Wrap,
) -> Result<Value>
where
    E: ExtensionDispatch,
    Wrap: FnOnce(CtxInner) -> E::Ctx,
{
    let (event_tx, _event_rx) = tokio::sync::mpsc::channel(1);
    let ctx_inner = stub_ctx_inner(event_tx);
    let ctx = wrap_ctx(ctx_inner);
    instance.dispatch_tool(tool_id, &ctx, params)
}

/// Build a `CtxInner` whose backends all return
/// `Error::Capability(... "not wired in v0.1 wasm flavour")`.
///
/// SCOPE R8 says wasm capability enforcement is *link-time* — a
/// component without `wasi:http/outgoing-handler` linked cannot even
/// call `http.request`. That covers the WASI side; the
/// `starter:extension/host` interface (where secrets / kv / tracing
/// would land) is reserved for v0.2 and currently has no host
/// implementation. The stub returns a typed `Error::Capability` so a
/// handler that calls an un-wired backend produces a deterministic
/// error rather than a panic — matching the process flavour's stub
/// shape (see `crate::process`).
fn stub_ctx_inner(events: EventSender) -> CtxInner {
    #[derive(Debug)]
    struct Stub(&'static str);
    impl SecretsBackend for Stub {
        fn get(&self, _name: &str) -> Result<String> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl HttpOutBackend for Stub {
        fn request(&self, _req: Value) -> Result<Value> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl FsBackend for Stub {
        fn read(&self, _path: &str) -> Result<Vec<u8>> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl WallClockBackend for Stub {
        fn now_unix_ms(&self) -> Result<u64> {
            // `wasi:clocks/wall-clock` is the link-time path; this
            // stub returns the host's clock so a handler that did not
            // declare `wall_clock` but somehow obtained a handle
            // still gets a deterministic value rather than panicking.
            // (The `requires!{}`-generated Ctx would not expose
            // `.wall_clock()` without the declaration, so this code
            // is rarely reached.)
            use std::time::{SystemTime, UNIX_EPOCH};
            Ok(SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0))
        }
    }
    impl TracingBackend for Stub {
        fn event(&self, _level: &str, _msg: &str, _fields: Value) {}
    }
    impl WarehouseReadBackend for Stub {
        fn query(&self, _template: &str, _params: Value) -> Result<Vec<Row>> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
        fn count(&self, _template: &str, _params: Value) -> Result<u64> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
        fn describe(&self, _template: &str) -> Result<Option<TemplateSpec>> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl WarehouseWriteBackend for Stub {
        fn insert(&self, _table: &str, _rows: Vec<Row>) -> Result<u64> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl DatasourceBackend for Stub {
        fn query(&self, _id: &str, _sql: &str, _params: Vec<Value>) -> Result<Vec<Row>> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
        fn execute(&self, _id: &str, _stmt: &str, _params: Vec<Value>) -> Result<u64> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl EventBusBackend for Stub {
        fn publish(&self, _topic: &str, _payload: Value) -> Result<()> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl DashboardBackend for Stub {
        fn read(&self, _page_id: &str) -> Result<Value> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
        fn write(&self, _page_id: &str, _body: Value) -> Result<()> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    impl AuthzBackend for Stub {
        fn check(&self, _action: &str, _resource: &str) -> Result<bool> {
            Err(Error::capability(format!(
                "{}: capability backend not wired in v0.1 wasm flavour",
                self.0
            )))
        }
    }
    CtxInner::new(
        events,
        Arc::new(NeverCancel),
        Arc::new(Stub("secrets")),
        Arc::new(Stub("http_out")),
        Arc::new(Stub("fs")),
        Arc::new(Stub("wall_clock")),
        Arc::new(Stub("tracing")),
        Arc::new(Stub("warehouse_read")),
        Arc::new(Stub("warehouse_write")),
        Arc::new(Stub("datasource")),
        Arc::new(Stub("event_bus")),
        Arc::new(Stub("dashboard")),
        Arc::new(Stub("authz")),
    )
}
